provisionPath = "initscripts/init.sh"

nodes = [
	{:hostname => "gmc3", :ip => "192.168.20.2", :cpus => 2, :mem => 1024, :provisionScript => provisionPath}
]


Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			vmachine.vm.box_download_insecure = true
			vmachine.vm.box = "peru/ubuntu-18.04-server-amd64"
			vmachine.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.network "private_network", ip: node[:ip]
			vmachine.vm.provider :virtualbox do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			vmachine.vm.provision :shell, path: node[:provisionScript]
		end
	end
end
